version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
    ports:
      - "6379:6379"
  # db: 
  #   image: postgres
  #   networks:
  #     - webnet
  #   environment:
  #     POSTGRES_PASSWORD: 
  #     POSTGRES_USER: 
  #     POSTGRES_DB: 
  #   ports:
  #     - "6666:5432"
  web:
    image: myservice
    ports:
      - "3004:3004"
    networks:
      - webnet
    depends_on:
      - redis
      - db
    environment:
      DB_HOST: db
      REDIS_HOST: redis
networks:
  webnet: